models not used

## ols model v1, Rec
 
```{r, fig.width=11, fig.height=3}
# do ols model

# define datadist
dd.dd = datadist(dd)
options(datadist = "dd.dd")
# build model
v1 <- ols(data=dd, RT_Rec ~ c_Vag + c_Num + c_Itm + c_Qty + c_Ord + s_Trl, x=T, y=T)
cat("R2 = ", v1$stats[4])
# show model
#v1
# show model summary
#summary(v1)
# do anova 
an1 = anova(v1)
# show anova
#an1
# generate predictions
p1=Predict(v1)
# plot 'partial effects'
plot(p1, anova=an1, pval=T, layout=c(6,1), aspect=1, main="ols model v1")
```

```{r, fig.width=9, fig.height=3}
# Baayen 4-plot model criticism

par(mfrow=c(1,4), pty='s')
# create scaled residuals
v1$rstand = as.vector(scale(resid(v1)))
# plot scaled residuals density
plot(density(v1$rstand))
# plot sample quantiles versus theoretical quantiles
qqnorm(v1$rstand, cex=.5)
qqline(v1$rstand)
# plot standardised residuals versus fitted values
plot(v1$rstand ~ fitted(v1), pch='.')
# absolute standardised residuals greater than 2.5 are candidates for being outliers, the abline identifies them on the plot
abline(h=c(-2.5,2.5))
# create dffits
dffits=abs(resid(v1, "dffits"))
# plot dffits
plot(dffits, type='h')
```

## ols model v2, Rec, with polynomials

```{r, fig.width=11, fig.height=3}
# do ols model

# define datadist
dd.dd = datadist(dd)
options(datadist = "dd.dd")
# build model
v2 <- ols(data=dd, RT_Rec ~ c_Vag * c_Num + pol(c_Itm,2) + c_Qty + c_Ord + pol(s_Trl,6) + c_Vag:c_Qty, x=T, y=T)
cat("R2 = ", v2$stats[4])
# show model
#v2
# show model summary
#summary(v2)
# do anova 
an1 = anova(v2)
# show anova
#an1
# generate predictions
p1=Predict(v2)
# plot 'partial effects'
plot(p1, anova=an1, pval=T, layout=c(6,1), aspect=1, main="ols model v2")
```

```{r, fig.width=9, fig.height=3}
# Baayen 4-plot model criticism

par(mfrow=c(1,4), pty='s')
# create scaled residuals
v2$rstand = as.vector(scale(resid(v2)))
# plot scaled residuals density
plot(density(v2$rstand))
# plot sample quantiles versus theoretical quantiles
qqnorm(v2$rstand, cex=.5)
qqline(v2$rstand)
# plot standardised residuals versus fitted values
plot(v2$rstand ~ fitted(v2), pch='.')
# absolute standardised residuals greater than 2.5 are candidates for being outliers, the abline identifies them on the plot
abline(h=c(-2.5,2.5))
# create dffits
dffits=abs(resid(v2, "dffits"))
# plot dffits
plot(dffits, type='h')
```

## ols model v3, RecSqt, with polynomials

```{r, fig.width=11, fig.height=3}
# do ols model

# define datadist
dd.dd = datadist(dd)
options(datadist = "dd.dd")
# build model
v3 <- ols(data=dd, RT_RecSqt ~ c_Vag * c_Num + pol(c_Itm,2) + c_Qty + c_Ord + pol(s_Trl,6) + c_Vag:c_Qty, x=T, y=T)
cat("R2 = ", v3$stats[4])
# show model
#v3
# show model summary
#summary(v3)
# do anova 
an1 = anova(v3)
# show anova
#an1
# generate predictions
p1=Predict(v3)
# plot 'partial effects'
plot(p1, anova=an1, pval=T, layout=c(6,1), aspect=1, main="ols model v3")
```

```{r, fig.width=9, fig.height=3}
# Baayen 4-plot model criticism

par(mfrow=c(1,4), pty='s')
# create scaled residuals
v3$rstand = as.vector(scale(resid(v3)))
# plot scaled residuals density
plot(density(v3$rstand))
# plot sample quantiles versus theoretical quantiles
qqnorm(v3$rstand, cex=.5)
qqline(v3$rstand)
# plot standardised residuals versus fitted values
plot(v3$rstand ~ fitted(v3), pch='.')
# absolute standardised residuals greater than 2.5 are candidates for being outliers, the abline identifies them on the plot
abline(h=c(-2.5,2.5))
# create dffits
dffits=abs(resid(v3, "dffits"))
# plot dffits
plot(dffits, type='h')
```





