---
output:
  html_document:
    toc: true
    <!--toc_float: true-->
    mathjax: default
    template: default
    code_folding: hide
    <!--theme: default-->
---


```{r}
load("dd.Rda")
suppressPackageStartupMessages(require(lme4))
suppressPackageStartupMessages(require(lmerTest))
suppressPackageStartupMessages(require(languageR))
```

```{r}
v5 <- lmer(data=dd, 
           RT_RecSqt ~ 
             c_Vag + c_Num + c_Qty + c_Ord + 
             c_Num:c_Vag:c_Qty +
             item_mean_ratio + 
             s_Trl +
             RTprev_RecSqt +
             nchar_instr +
             (1+c_Vag + c_Num + c_Qty + c_Ord|Subject)
)
```

```{r}
summary(v5)
```

```{r}
cat("R^2")
cor(fitted(v5), dd$RT_RecSqt)^2
```

```{r}
par(mfrow=c(2,5))
plotLMER.fnc(v5)
```

Plot model coefficients and ci's

```{r}
par(las=2, mar=c(14,6,1,1))
y=as.data.frame(summary(v5)$coef[-1,1]) # estimates, without intercept
q=confint(v5)[-c(1,2,3),]
y=cbind(y,q)
plot(y[,1], ylim=range(y[,1],y[,2],y[,3]), xaxt="n", xlab="", ylab="estimate\n",  pch='-', cex=2)
segments(x0=1:nrow(y), x1=1:nrow(y), y[,2], y[,3])
abline(h=0)
axis(1, labels=row.names(y), at=1:nrow(y), srt=45)
grid()
```


Model criticism baayen plots

```{r, fig.width=9, fig.height=3}
# Baayen 4-plot model criticism

par(mfrow=c(1,4), pty='s')
# create scaled residuals
v5$rstand = as.vector(scale(resid(v5)))
# plot scaled residuals density
plot(density(v5$rstand))
# plot sample quantiles versus theoretical quantiles
qqnorm(v5$rstand, cex=.5)
qqline(v5$rstand)
# plot standardised residuals versus fitted values
plot(v5$rstand ~ fitted(v5), pch='.')
# absolute standardised residuals greater than 2.5 are candidates for being outliers, the abline identifies them on the plot
abline(h=c(-2.5,2.5))
# create dffits
dffits=abs(resid(v5, "dffits"))
# plot dffits
plot(dffits, type='h')
```