---
title: "Experiment 1 of 4"
author: "Matt Green"
output:
  html_document:
    toc: yes
    <!--toc_float: true-->
    mathjax: default
    template: default
    code_folding: hide
    theme: default
---  

<style type="text/css">
.table {width: 50%;}
</style>

vagueness |instruction
----------|-------------------------------------------------------------------
crisp     |Choose the the square with many dots
vague     |Choose the square with 20 dots 

items| a
-----|-----
1    |5,25
2    |10,25
3    |15,25
4    |20,25
-----|-----
5    |30,25
6    |35,25
7    |40,25
8    |45,25

In this experiment it was possible to identify errors, so error trials were removed. This is because there were only 2 squares and an istruction uniquely identified one of them.

# Prep data

```{r prepData}
rm(list=ls())
suppressPackageStartupMessages(library(knitr))
#opts_chunk$set(cache=TRUE, autodep=TRUE)
#opts_chunk$set(size="footnotesize")
#options(width=60)
```

```{r loadLibs}
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(xtable))
suppressPackageStartupMessages(library(plyr))
suppressPackageStartupMessages(library(reshape2))
suppressPackageStartupMessages(library(lattice))
suppressPackageStartupMessages(library(car))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(lme4))
suppressPackageStartupMessages(library(LMERConvenienceFunctions))
suppressPackageStartupMessages(library(lmerTest))
```

```{r sourceFunctions}
source("CIfunctions.R")
```

## get data

```{r manipulateDataFrame, echo=FALSE}
system("cat ../experimentCode/output/*.dat > ../data/data.txt", wait=TRUE)
dat <- read.delim("../data/data.txt", header=FALSE)
names(dat) <- c("condition", "leftN", "rightN", "vgn", "side", "string", "subject", "rt", "error")
dat$subject <- as.factor(paste("sub",sep="",sprintf("%02d",dat$subject,sep="")))
dat$error <- 1-dat$error
dat$Ord <- ifelse(dat$leftN < dat$rightN, 'LtoR', 'RtoL')
dat$c_Ord <- ifelse(dat$Ord=='LtoR', -.5, .5)
dat$bigside <- ifelse(dat$leftN > dat$rightN, 'L', 'R')
dat$Qty <- ifelse(dat$side==dat$bigside, "Large", "Small")
dat$bigside=NULL
dat$c_Qty <- ifelse(dat$Qty=='Small', -.5, .5)
dat$gap <- as.character(paste("gap", sep=" ", sprintf("%02d",abs(dat$leftN-dat$rightN))))
dat$vgn <- as.factor(ifelse(dat$vgn=="P", "Crisp", "Vague"))
dat$c_Vgn <- ifelse(dat$vgn=='Crisp', -.5, .5)
dat$logrt <- log(dat$rt)
# item_ratio
# NOT DONE YET
write.table(x=dat, "all_trials.txt")
dat$subject <- as.factor(dat$subject)
dat$vgn <- ifelse(dat$vgn=='Crisp', -.5, .5)
dat$gap[dat$gap=="gap 05"] <- -1.5
dat$gap[dat$gap=="gap 10"] <- -.5
dat$gap[dat$gap=="gap 15"] <- .5
dat$gap[dat$gap=="gap 20"] <- 1.5
dat$gap <- as.numeric(dat$gap)
# Separate off correct trials
alltrials <- dat
correct <- subset(dat, error==0)
errors <-  subset(dat, error==1)
```

# RT model

```{r tableRTmodel, results='asis'}
print(
	xtable(
		digits=3, 
		summary(
			rt.lmer <- lmer(data=correct, logrt~gap*vgn + (vgn|subject))
			)$coefficients,
		caption="Most maximal response time model", 
		caption.placement="top"), type='html')
```

## RT means

For correct rts df, show means. Vagueness appears to be beneficial.

```{r plotCorrectRTMeans, fig.width=3, fig.height=3}
a <- summarySEwithin(correct,  measurevar="logrt",  withinvars=c("vgn"),  idvar="subject")
ggplot(data=a, aes(y=logrt_norm, x=vgn, group=1, ymin=logrt_norm-ci, ymax=ci+logrt_norm)) + geom_line() + geom_point() + geom_errorbar(width=.05) + xlab("") + ylab("log rt") + theme_bw() + theme(aspect.ratio=1) 
```

# Error rates model

```{r tableErrorModel, results='asis'}
print(xtable(digits=3, summary(ac.lmer <- 
															 	glmer(data=alltrials, error~gap*vgn + (gap+vgn|subject), 
															 				family="binomial", 
															 				control = glmerControl(optimizer = "bobyqa")))$coefficients,
						 caption="Most maximal accuracy model",
						 caption.placement="top"),type='html')
```

```{r qq, fig.width=5, fig.height=3}
op <- par(mfrow=c(1,2))
qqPlot(residuals(rt.lmer), cex=.2)
qqPlot(residuals(ac.lmer), cex=.2)
```

```{r plotMeansBoth, fig.width=10, fig.height=4, message=FALSE}
rts <- summarySEwithin(correct, measurevar="logrt", withinvars=c("vgn","gap"))
err <- summarySEwithin(alltrials, measurevar="error", withinvars=c("vgn","gap"))
dodge=.06

plot1 =
  ggplot(rts, aes(y=logrt_norm, x=gap, group=vgn, fill=vgn, shape=vgn, ymin=logrt_norm-ci, ymax=logrt_norm+ci)) + 
  geom_line(position=position_dodge(dodge)) + 
  geom_errorbar(width=.3, lty=1, position=position_dodge(dodge)) + 
  geom_point(pch=21, size=3, position=position_dodge(dodge)) +
  ggtitle("Response time") + 
  ylab("log RT") + 
  xlab("Gap Size") +
  scale_fill_grey(name=element_blank(), start=0,end=1)+
  theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), legend.key = element_blank() ) +
  theme(aspect.ratio=1)+xlab("")

plot2 = 
  ggplot(err, aes(y=error_norm, x=gap, group=vgn, fill=vgn, shape=vgn, ymin=error_norm-ci, ymax=error_norm+ci)) + 
  geom_line(position=position_dodge(dodge)) + 
  geom_errorbar(width=.3, lty=1, position=position_dodge(dodge)) + 
  geom_point(pch=21, size=3, position=position_dodge(dodge)) +
  ggtitle("Error rate") + 
  ylab("error rate") + 
  xlab("Gap Size") +
  scale_fill_grey(name=element_blank(), start=0,end=1)+
  theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), legend.key = element_blank() )+
  theme(aspect.ratio=1)+xlab("")

grid.arrange(plot1,plot2,ncol=2)
```
