Vagueness experiment 4 models
========================================================

```{r loaddata, echo=FALSE}
rm(list=ls())
load("e4vagueness.RData")
source("CIfunctions.R")
```

```{r loadlibs}
suppressPackageStartupMessages(library(lme4,quietly=TRUE,warn.conflicts=FALSE))
suppressPackageStartupMessages(library(lmerTest,quietly=TRUE,warn.conflicts=FALSE))
```

Set anova contrasts

```{r setAnovaContrast}
anova.contrast <- matrix(c(-.5,-.5,.5,.5, -.5,.5,-.5,.5, .5,-.5,-.5,.5), 4,3,                      dimnames = list(c("comparison:crisp", "comparison:vague", "matching:crisp", "matching:vague"),  c("selection", "vagueness", "selectionXvagueness")))  
contrasts(x$Effect) <- anova.contrast
```

Do omnibus lmer using custom anova contrast.

```{r maximalLMERrt}
maximal.lmer <- lmer(data=x, logRT ~ Effect + (Effect|Item) + (Effect|Subject))
```

Planned comparisons crisp versus vague at each level of selection.

Comparison vague versus comparison crisp.

```{r comparisonLMERrt}
comparison.lmer <- lmer(data=x, subset=selection=="comparison", logRT ~ vagueness +  (vagueness|Item) + (vagueness|Subject))
```

Matching vague versus matching crisp.

```{r matchingLMERrt}
matching.lmer <- lmer(data=x, subset=selection=="matching", logRT ~ vagueness  + (vagueness|Item) + (vagueness|Subject))
```




```{r}
maximal.lmer
comparison.lmer
matching.lmer
```


PLot the comparison vague versus comparison crisp

```{r}
x2 <- subset(x, subset=selection=="comparison", select=c(Subject,vagueness,RT))
x3 <- summarySEwithin(x2,measurevar="RT",withinvars="vagueness",idvar="Subject")
ggplot(data=x3,aes(y=RT,x=vagueness,ymin=RT-ci,ymax=RT+ci,group=vagueness,stat="identity"))+geom_errorbar(width=.2)+geom_point()

```
