---
title: "Experiment 2 of 4"
author: "Matt Green"
output:
  html_document:
    toc: yes
    toc_float: true
    mathjax: default
    template: default
    <!--code_folding: show-->
    theme: default
---  

<style>
table, th, td {
    border: 1px grey;
    border-collapse: collapse;
    padding:2px 5px 2px 5px
}  
</style>

In this experiment we did not count any response as an error, instead we coded them as expected, borderline, and extreme.

# 2017

```{r "set working directory to 2017_submitted_to_springer"}
root="/home/matt/wd/vagueness/experiments/e2/writeup/2017_submitted_to_springer"
if (getwd() != root) setwd("2017_submitted_to_springer")
```

```{r load Libraries, message=FALSE, echo=FALSE}
library(knitr); library(Matrix); library(ggplot2); library(xtable); library(gridExtra); library(lme4); library(lmerTest);  library(data.table); library(dplyr); library(dtplyr); library(pander); library(LMERConvenienceFunctions) 
```

```{r "source my functions", message=FALSE, echo=FALSE}
source('../functions/summarySEwithin2.R')
source('../functions/e2-preprocessing.R')
```

```{r showInstructions, echo=FALSE}
v = c("crisp", "crisp", "vague", "vague")
n = c('number', 'word', 'number', 'word')
e <- c("Choose the square with 6 dots", "Choose the square with the fewest dots", "Choose a square with about 10 dots", "Choose a square with few dots")
i = data.frame(v, n, e)
names(i) = c("vagueness", "number", "example instruction")
pander(i, justify=c('center', 'left', 'left'))
```

```{r showItems, echo=FALSE}
items = c(1,2,3,4,5,6,7,8)
i = data.frame(Item = c("1","2","3","4"),
               x = c("06:15:24", "16:25:34", "26:35:44", "36:45:54"))
names(i) = c('Item', 'Numbers of dots')
pander(i, justify=c('center', 'center'))
```

```{r preprocessing, echo=FALSE, message=FALSE}
if( !file.exists('e2-data.txt') ) {
  dat <- gatherData() 
  dat <- declareImpossibleRT(dat)
  #dat <- removeImpossibleTrials(dat)
  dat <- subset(dat, select=c(Subject, Trial, Item, c_Itm, 
                              discriminability, 
                              Instruction,
                              nchar_instr,
                              Vagueness, Number, Order, Quantity, 
                              c_Vag, c_Num, c_Ord, c_Qty,
                              NaType, response_category, 
                              isBorderline, RT, RT_log)
  )
  write.table(dat, file='e2-data.txt', sep='\t', quote=FALSE, row.names = FALSE)
}
```

```{r getData, echo=TRUE, tidy=FALSE}
rawdata <- read.delim('e2-data.txt')
tempdata <- perSubjectTrim.fnc(data = rawdata[complete.cases(rawdata),], 
                               response='RT', subject='Subject', trim = 2.5)$data
rtdata <- tempdata
bldata <- tempdata
```

```{r e2-rtplot, fig.width=7, fig.height=3.5, echo=FALSE, message=FALSE}
rtdataplot1 <- summarySEwithin2(rtdata, 
                                measurevar="RT_log", 
                                withinvars=c("Vagueness", "Number", "Item"), idvar="Subject")
rtdataplot1$Condition <- as.factor(paste(sep=':', rtdataplot1$Number, rtdataplot1$Vagueness))
rtplot=ggplot(rtdataplot1, aes(y=RT_logNormed, x=Item, group=Condition, fill=Vagueness)) +
  geom_line() +
  geom_errorbar(width=.2, aes(ymin=RT_logNormed-ci, ymax=RT_logNormed+ci)) +
  geom_point(size=2, col=1, aes(shape=Vagueness)) +
  scale_fill_grey(name="Vagueness", start=0, end=1) +
  scale_shape_manual(name="Vagueness", values=c(21,22)) +
  ggtitle("Response time") +
  ylab("Respone time (log (ms))") + 
  xlab(NULL) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        legend.key = element_blank(), legend.position="right",
        aspect.ratio=1,
        plot.background=element_rect(fill=NA, color='white'),
        strip.background=element_blank(),
        axis.text.x = element_text(angle = 15)) +
  facet_grid(~Number)
rtplot
```

```{r e2-blBarChart, fig.width=7, fig.height=3.5, echo=FALSE, message=FALSE}
bldata$response_category <- relevel(bldata$response_category, ref='expected')
blBarChart = ggplot(bldata) +
  geom_bar(aes(response_category, group=Number:Vagueness, fill=Vagueness),
           position=position_dodge(width=NULL)) +
  scale_fill_grey() +
  xlab(NULL) +
  ggtitle('Borderline response distribution') +
  facet_grid(~Number) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        legend.key = element_blank(), legend.position="right", 
        aspect.ratio=1,
        plot.background=element_rect(fill=NA, color='white'),
        strip.background=element_blank(),
        legend.key.size=unit(4, 'mm'),
        axis.text.x = element_text(angle = 15))
blBarChart
```

Response time models 

```{r e2-rtlmerTest1, cache=TRUE, echo=TRUE}
rtlmerTest1 = lmerTest::lmer(
  data=rtdata,
  RT_log ~ c_Vag * c_Num + c_Itm +
    (1 + c_Vag * c_Num + c_Itm | Subject))
```

```{r e2-rtlmerTest1Visuals, cache=FALSE, echo=FALSE, results='asis', dependson='e2-rtlmerTest1', fig.width=6, fig.height=3}

# print a table of coefficients
print(
  xtable(
    summary(rtlmerTest1)$coefficients[,-3], 
    display=c("s","f","f","f","f"),
    digits=c(0,2,2,1,3),
    caption="Response time model"),
  caption.placement="top", 
  type='html')

# make a data frame for plotting coefficients of rtlmerTest1
dfr <- data.frame(coef = summary(rtlmerTest1)$coef[,1],
                  ci2.5 = confint(rtlmerTest1, method='Wald')[,1][!is.na(confint(rtlmerTest1, method='Wald')[,1])],
                  ci97.5 = confint(rtlmerTest1, method='Wald')[,2][!is.na(confint(rtlmerTest1, method='Wald')[,2])]
)
intercept = round(dfr[1,1],2)
dfr <- dfr[-1,] # lose the intercept for plotting
dfr <- dfr[rev(rownames(dfr)),]

# plotting code for plotting coefficients of rtlmerTest1
par(mar=c(5,7,2,1))
plot(y=1:nrow(dfr), 
     x=dfr$coef, 
     xlim=extendrange(range(dfr$ci2.5, dfr$ci97.5)), 
     ylim=extendrange(c(1,nrow(dfr))),
     type='n', axes=F, 
     xlab=substitute(paste('deviation from an intercept of ', intercept, ' log RT, with 95% CI.'), list(intercept=intercept)),
     ylab="",
     main = 'Response time model')
abline(v=0, lty=1, col='lightgrey')
arrows(y0=1:nrow(dfr), y1=1:nrow(dfr), 
       x0=dfr$ci2.5, x1=dfr$ci97.5, 
       length=0.035,
       col='black',
       lwd=2, code=3, angle=90)
points(y=1:nrow(dfr), x=dfr$coef, pch=21, bg='white')
axis(2, labels=row.names(dfr), at=1:nrow(dfr), las=1, tick=FALSE)
axis(1)
box(which='plot', col='grey')
```

```{r e2-seplmerforNum, results='asis', cache=TRUE}

# make data for numeric-only model
numOnly <- subset(rtdata, subset=Number=='Numeric')

# run lmer for numeric-only model
numOnlylm <- lmerTest::lmer(data=numOnly, RT_log ~ c_Vag + c_Itm + (1 + c_Vag + c_Itm | Subject))

# print coefficients for numeric-only model
print(
  xtable(
    summary(numOnlylm)$coefficients[,-3], 
    display=c("s","f","f","f","f"),
    digits=c(0,2,2,1,3),
    caption="Response time model: Numeric only"),
  caption.placement="top", 
  type='html')
```

```{r e2-seplmerforVerbal, results='asis', cache=TRUE}
# make data for verbal-only model
verbalOnly <- subset(rtdata, subset=Number=='Verbal')

# run lmer for verbal-only model
verbalOnlylm <- lmerTest::lmer(data=verbalOnly, RT_log ~ c_Vag + c_Itm + (1 + c_Vag + c_Itm | Subject))

# print coefficients for verbal-only model
print(
  xtable(
    summary(verbalOnlylm)$coefficients[,-3], 
    display=c("s","f","f","f","f"),
    digits=c(0,2,2,1,3),
    caption="Response time model: Verbal only"),
  caption.placement="top", 
  type='html')
```

Borderline response models

```{r e2-bllmer, cache=TRUE, echo=TRUE}
bllmer = lme4::glmer(data=bldata,
                        isBorderline ~ c_Vag * c_Num + c_Itm +
                          (1 + c_Vag * c_Num + c_Itm | Subject),
                        family="binomial", control = glmerControl(optimizer = "bobyqa"))
```

```{r e2-bllmerVisuals, cache=FALSE, echo=FALSE, results='asis', dependson='e2-bllmer', fig.width=6, fig.height=3}
print(
  xtable(
    summary(bllmer)$coefficients,
    digits=c(0, 2, 2, 1, 3),
    caption="Error rates model"),
  caption.placement="top", 
  type='html')
dfr <- data.frame(coef = summary(bllmer)$coef[,1],
                  ci2.5 = confint(bllmer, method='Wald')[,1][!is.na(confint(bllmer, method='Wald')[,1])],
                  ci97.5 = confint(bllmer, method='Wald')[,2][!is.na(confint(bllmer, method='Wald')[,2])]
)
intercept = round(dfr[1,1],2)
dfr <- dfr[-1,] # lose the intercept for plotting
dfr <- dfr[rev(rownames(dfr)),]
par(mar=c(5,7,2,1))
plot(y=1:nrow(dfr), 
     x=dfr$coef, 
     xlim=extendrange(range(dfr$ci2.5, dfr$ci97.5)), 
     ylim=extendrange(c(1,nrow(dfr))),
     type='n', axes=F, 
     xlab=substitute(paste('deviation from an intercept of ', intercept, ' with 95% CI.'), list(intercept=intercept)),
     ylab="",
     main='Borderline response model')
abline(v=0, lty=1, col='grey')
arrows(y0=1:nrow(dfr), y1=1:nrow(dfr), 
       x0=dfr$ci2.5, x1=dfr$ci97.5, 
       length=0.035,
       col='black',
       lwd=2, code=3, angle=90)
points(y=1:nrow(dfr), x=dfr$coef, pch=21, bg='white')
axis(2, labels=row.names(dfr), at=1:nrow(dfr), las=1, tick=FALSE)
axis(1)
box(which='plot', col='grey')
```

