---
title: "Experiment 2 of 4"
author: "Matt Green"
output:
  html_document:
    toc: yes
    <!--toc_float: true-->
    mathjax: default
    template: default
    <!--code_folding: show-->
    theme: default
---  
<style>
table, th, td {
    border: 1px grey;
    border-collapse: collapse;
    padding:2px 5px 2px 5px
}  
</style>


```{r setup, include=FALSE, cache=FALSE}
library(knitr)
```

```{r loadFonts, message=FALSE, echo=FALSE}
library(fontcm)
library(extrafont)
#font_import()
#loadfonts()
```

```{r loadLibs, message=FALSE, echo=FALSE}
library(beepr)                     #
library(car)                       #
library(ggplot2)                   #
library(grid)                      #
library(gridExtra)                 #
library(languageR)                 #
library(lattice)                   #
library(latticeExtra)              # for doubleYScale
library(lme4)                      #
library(lmerTest)                  #
library(LMERConvenienceFunctions)  # for perSubjectTrim
library(MASS)                      #
library(plyr)                      #
library(reshape2)                  #
library(rms)                       # for varclus
library(Rmisc)                     # for summarySEwithin and friends
library(xtable)                    #
```

```{r preprocessing}
source('e2-preprocessing.R')
if( !file.exists('e2-b-data.txt') ) {
  dat <- gatherData() 
  dat <- declareImpossibleRT(dat)
  dat <- removeImpossibleTrials(dat)
  dat <- subset(dat, select=c(Subject, Trial, Item, 
                              discriminability, 
                              Instruction,
                              nchar_instr,
                              Vagueness, Number, Order, Quantity, 
                              c_Vag, c_Num, c_Ord, c_Qty,
                              NaType, response_category, 
                              isBorderline, RT)
  )
  write.table(dat, file='e2-b-data.txt', sep='\t', quote=FALSE)
}
dd <- read.delim('e2-b-data.txt')
```

```{r showCompression, fig.width=6, fig.height=4, fig.pos='hbtp', fig.cap='Ratios for different numbers of dots in the arrays: smaller values are more discriminable. Blue is for the ratio between the smallest number in the array and the largest number in an array. Red is for the mean of two ratios, one for the smallest number to the middle number, the other for the middle number to the largest number in the array', echo=FALSE}
#  Show compression of ratios of numbers of dots in the items
discriminability = sort(unique(as.numeric(dd$discriminability)))
plot(y=c(1.5,1.5,1.5,1.5), 
     x=discriminability, 
     ylab='',
     xlab='',
     yaxt='n',
     type='n', 
     xaxt='n',
     axes=F)
lines(y=c(1.5,1.5,1.5,1.5), x=discriminability, type='o', pch=19)
text(y=c(1.15,1.15,1.15,1.15), x=discriminability, labels=round(discriminability,2),  cex=.7)
mtext('mean (ratio min/med,\nratio med/max)', side = 2, line = 1)
mtext('Discriminability index', side=1, line=3)
mtext('Discriminability for each item', side=3, line=1, cex=1.5)
axis(1)
box(which='plot', col='grey')
```

```{r e2-rtplot, fig.width=7, fig.height=3.5, echo=FALSE, message=FALSE, dev='pdf'}
dd$RT_log=log(dd$RT)
rtdata=dd
source('summarySEwithin2.R')
rtdataplot1 <- summarySEwithin2(rtdata, measurevar="RT_log", 
                                withinvars=c("Vagueness", "Number", "Item"), idvar="Subject")
rtdataplot1$Condition <- as.factor(paste(sep=':', rtdataplot1$Number, rtdataplot1$Vagueness))
rtplot=ggplot(rtdataplot1, aes(y=RT_logNormed, x=Item, group=Condition, fill=Vagueness)) +
  geom_line() +
  geom_errorbar(width=.2, aes(ymin=RT_log-ci, ymax=RT_log+ci)) +
  geom_point(size=2, col=1, aes(shape=Vagueness)) +
  scale_fill_grey(name="Vagueness", start=0, end=1) +
  scale_shape_manual(name="Vagueness", values=c(21,22)) +
  ggtitle("Response time") +
  ylab("Respone time (log (ms))") + 
  xlab(NULL) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        legend.key = element_blank(), legend.position="top",
        aspect.ratio=1,
        plot.background=element_rect(fill=NA, color='white'),
        strip.background=element_blank(),
        axis.text.x = element_text(angle = 15)) +
  facet_grid(~Number)
rtplot
```
#Lmer model: before outlier removal

```{r}
dd$RT_log <- log(dd$RT)
dd$c_Trl <- as.numeric(scale(dd$Trial))
```


```{r lmer5, tidy=FALSE, cache=TRUE}
vlmerTest <- lmerTest::lmer(data=dd,
                 RT_log ~
                   c_Vag + c_Num + c_Qty + c_Ord +
                   c_Num:c_Vag:c_Qty +
                   discriminability +
                   c_Trl +
                   #RTprev_log +
                   nchar_instr +
                   (1+c_Vag + c_Num + c_Qty + c_Ord|Subject))
```



```{r printXtableV5, echo=FALSE, results='asis'}
print(
  xtable(
    summary(vlmerTest)$coef,
    caption = 'lmerTest version',
    digits=c(0, 3,3,1,1,4)),
  type='html',
  caption.placement='top'
)
```


```{r llmer5, tidy=FALSE, cache=TRUE}
vlme4 <- lme4::lmer(data=dd,
                 RT_log ~
                   c_Vag + c_Num + c_Qty + c_Ord +
                   c_Num:c_Vag:c_Qty +
                   discriminability +
                   c_Trl +
                   #RTprev_log +
                   nchar_instr +
                   (1+c_Vag + c_Num + c_Qty + c_Ord|Subject))
```

```{r printXtableV521c, echo=FALSE, results='asis'}
print(
  xtable(
    summary(vlme4)$coef,
    caption = 'lme4 version',
    digits=c(0, 3,3,1)),
  type='html',
  caption.placement='top'
)
```

```{r, echo=1:3}
dfr <- data.frame(coef = summary(vlme4)$coef[,1], 
                  ci2.5  = confint(vlme4, method='Wald')[17:25, 1],
                  ci97.5 = confint(vlme4, method='Wald')[17:25, 2] )
dfr <- dfr[-1,]
dfr <- dfr[rev(rownames(dfr)),]
par(mar=c(5,10,1,1))
plot(y=1:nrow(dfr), 
     x=dfr$coef, 
     xlim=range(dfr$ci2.5, dfr$ci97.5), 
     type='n', axes=F, xlab="", ylab="")
abline(v=0, lty=3, col='grey')
abline(h=c(1,2,3,4,5,6,7,8,9), col='grey', lty=3)
arrows(y0=1:nrow(dfr), y1=1:nrow(dfr), 
       x0=dfr$ci2.5, x1=dfr$ci97.5, 
       length=0.035,
       col='black',
       lwd=2, code=3, angle=90)
points(y=1:nrow(dfr), x=dfr$coef, pch=21, bg='white')
axis(2, labels=row.names(dfr), at=1:nrow(dfr), las=1, tick=FALSE)
axis(1)
#mtext("Coefficient estimates, in units of log(RT),\nwith 95% confidence intervals", side=1, line=4, cex.lab=1, las=1)
#mtext("Model terms", side=2, line=8)
mtext('estimate with 95% CI', side=1, line=3, cex=.75)
box(which='plot', col='grey')
```

