---
title: "Experiment 2 of 4: main"
author: "Matt Green"
output:
  html_document:
    toc: true
    <!--toc_float: true-->
    mathjax: default
    template: default
    code_folding: hide
    theme: default
---

```{r child="print_info_on_design.Rmd"}
```

# Distributional stuff, including transformations.

```{r child = 'transformations_table.Rmd'}
```

```{r child = 'libraries.Rmd'}
```

```{r child = 'data_wrangling.Rmd'}
```

```{r child = 'plot_transformations_against_normal_equivalents.Rmd'}
```

# Now working with a data set without impossible trials.

```{r child = 'plot_boxplot_subjects_and_items.Rmd'}
```

```{r child = 'plot_fast_and_slow_subjects_and_items.Rmd'}
```

```{r child = 'plot_fast_and_slow_subjects_and_items_RecSqt.Rmd'}
```

```{r child = 'plot_practice_and_fatigue_effects.Rmd'}
```

# Plot main effects and interactions

```{r child = 'plot_interaction_effects.Rmd'}
```

# Show compression of item ratios

```{r child = 'show_compression_of_ratios.Rmd'}
```

# Model ols()

```{r child = "model_ols_1_with_baayen4plot_model_criticism.Rmd"}
```

# Model lmer()

```{r child = "model_lmer_0.Rmd"}
```
